### ISSUE TITLE
Switch to active page for Next.js

### ISSUE THREAD

**Issue by digitarald** [microsoft/vscode-livepreview#133]
Issue Type: <b>Feature Request</b>

As I am running my react/next/vue runtime, it would be great if Live Preview could sprinkle in its magic to switch to the right page in preview as I move between pages/routes.

Extension version: 0.2.6
VS Code version: Code - Insiders 1.59.0-insider (e437d424c5e6de97632f5513229c7ebc2cf27a32, 2021-07-28T05:12:37.003Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No
Remote OS version: Linux x64 5.10.25-linuxkit
Remote OS version: Linux x64 5.10.25-linuxkit

**Comment by andreamah** [comment]
Upon reading https://nextjs.org/docs/advanced-features/custom-server, this seems possible. However, it seems that we'd need to have next.js as an npm dependency since we would need to `require('next')` in the server. I would rather not ship live preview with a dependency on nextjs, so I'll close the issue for now. I'm open for feedback on this, though.
