### ISSUE TITLE
Setting variables on window doesn't work

### ISSUE THREAD

**Issue by mendeljacks** [microsoft/vscode-livepreview#159]
I'm not sure why but global variables are not coming to the dev tools pane.

The following works in a browser but not in live preview
```
<script>
  window.myVariable = 'test'
</script>

```
I also notice window.alert doesn't work either so maybe the whole window object is disabled?

ps I love how fast this plugin is, and would be interested to know engineering reasons behind why this is the case
even if a fix is not planned.

**Comment by andreamah** [comment]
Sorry for the late reply! If you're wondering why particularly that assigning something to `window` in the preview doesn't show in the variables in the devtools console, that's because the devtools pane opens at top by default. 
<img width="246" alt="image" src="https://user-images.githubusercontent.com/31675041/207118769-97fe53d2-8e45-4ace-aaa3-1d664e9afd4b.png">
You'd need to switch to the frame that hosts the content, which should show in the dropdown. 

The reason that window.alert() particularly doesn't work is likely because the alert can't be naturally handled by the webview or the iframe blocks it somewhere. The issue is tracked in #154
