### ISSUE TITLE
Local paths neither working down tree or from other drives

### ISSUE THREAD

**Issue by cwinstrol** [microsoft/vscode-livepreview#194]
Consider the local file path /root/dev/index.html

I'm able to successfully link files such as CSS up the file tree such as /root/dev/css/main.css

However I'm unable to link any files down the file tree such as /root/root-folder-css.css or from any other physical/external drive using either forward or backward slashes.

Thank you.

**Comment by andreamah** [comment]
If you're trying to preview a file that is outside of the current vscode workspace folder (or an upstream file from and out-of-workspace file's location), the server won't serve it because that would pose as a security threat. It would essentially be possible for the server to serve any file on your computer, which isn't ideal.
