### ISSUE TITLE
Running task name is too vague

### ISSUE THREAD

**Issue by alevroub** [microsoft/vscode-livepreview#210]
Running the server along with other long-running tasks becomes unintuitive when the process name is called "[Run Server](https://github.com/microsoft/vscode-livepreview/blob/df0800bc59da17fe0e778b014c7b86dd523b877f/src/utils/constants.ts#L33)". A more relevant and appropriate name for the process could simply be _Live Preview_, or _Live Preview Server_, etc.

**Comment by andreamah** [comment]
It's a bit tricky to call it something like "Live Preview Server" or something that has "Live Preview" in it because the process of manually selecting a task shows task names as "{Script Type}: {Task Name}". 
In Live Preview's case, it's "Live Preview: Run Server". If I changed "Run Server" to "Live Preview Server", the task would look like "Live Preview: Live Preview Server" from the task picker, which would look odd.

<img width="439" alt="image" src="https://user-images.githubusercontent.com/31675041/206313928-59acd767-8896-4b1d-a1ad-b926ea1e31b3.png">

If you're cool with just running the task by itself, you can have a `tasks.json` with 
```
{
    "tasks": [
        {
            "type": "Live Preview",
            "workspacePath": "{the path to your workspace}",
            "problemMatcher": [],
            "label": "Live Preview Server",
        }
    ]
}
```
And just run it from the `Run Task` command. This will run it with the name that you give in the label as the terminal name.
