### ISSUE TITLE
livePreview.autoRefreshPreview "On Changes to Saved Files" not working anymore

### ISSUE THREAD

**Issue by infacto** [microsoft/vscode-livepreview#235]
I added the option to the settings.json to only auto reload the page on save. It worked some time ago.

```json
{
  "livePreview.autoRefreshPreview": "On Changes to Saved Files",
}
```

But today it stopped working.

Live Preview Version: 0.2.12

VSCode Version: 1.68.1 (user setup)
Commit: 30d9c6cd9483b2cc586687151bcbcd635f373630
Date: 2022-06-14T12:48:58.283Z
Electron: 17.4.7
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Windows_NT x64 10.0.19042

**Comment by konsth191** [comment]
I went to the settings to find an option to only reload on save (because I'm getting flickering on refresh) and noticed that this option does appear to do nothing. To clarify, for me, it never refreshes the preview with this option set, also not on save. It's supposed to make it refresh on save?

I also would like to mention that the name `"On Changes to Saved Files"` is not very clear to me. How about `"On saving changes"` or something similarly simple?

**Comment by andreamah** [comment]
@infacto Are you still having this issue? I'm not seeing an issue with `"livePreview.autoRefreshPreview": "On Changes to Saved Files"`. What particularly is happening when you save?

@konsth191 I'll file another issue for this.

**Comment by allefeld** [comment]
I have a related problem, not sure whether it is the same. I can file a separate issue if not.

I use the extension to view HTML files which are __not edited__ in VS Code. Instead, a source file is edited, upon save this gets processed into HTML by an external program, which writes a new version of the HTML file. I have set "Auto Refresh Preview" to "On Changes to Saved Files".

This used to work (save of source leads to display of new version), but recently I've got the problem that apparently the refresh is triggered too early, so that the view is refreshed (flickers), but afterwards it still shows the old version of the HTML file. A workaround is to save the source again, triggering another write and another refresh, which this time is correct. Manually refreshing (↻) works, too.

I'm not entirely sure how this happens: If the refresh is triggered by the external program *starting* to write the new version, I would expect an incomplete version to be shown. Instead, it is simply the old version.

A solution might be related to #233?

**Comment by andreamah** [comment]
New filewatching was implemented in https://github.com/microsoft/vscode-livepreview/pull/309, but this follows the limitation that out-of-workspace files only refresh the preview if they're being updated in the editor (following a limitation in vscode's new filewatch). If your HTML code is auto-generated, and outside of the workspace, we currently don't have a solution for it and https://github.com/microsoft/vscode-livepreview/issues/233 may help with that one.
