### ISSUE TITLE
Could this tool tip have links to close these ports?

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode-livepreview#291]
Testing Microsoft/vscode#158835

![image](https://user-images.githubusercontent.com/2644648/186524854-f5a8a393-e788-4e59-9c1a-f30124755832.png)

Something like:
```
* 3999 (close)
```

and close runs the command that closes that server.

**Comment by andreamah** [comment]
related: #279

**Comment by andreamah** [comment]
@TylerLeonhardt Do you know where else we support links in status bar tooltips from extensions? I'm not sure whether links in tooltips is possible.

**Comment by TylerLeonhardt** [comment]
If I had to guess, it's the fact that the [tooltip can be a MarkdownString](https://code.visualstudio.com/api/references/vscode-api#StatusBarItem).

Here's an example from GitLens:
![image](https://user-images.githubusercontent.com/2644648/187295888-29d7284b-8753-4f0a-9a37-4e1e70ea72dc.png)

**Comment by andreamah** [comment]
I currently have this in mind for choosing a particular server to close. Do you think you'd still prefer a link on the tooltip in addition? I'm just worried that it'll make the tooltip look too busy (especially since I added the workspace names since you last tested).
![Recording 2022-08-29 at 14 00 56](https://user-images.githubusercontent.com/31675041/187298103-82b223a4-a2a0-497c-a9a2-d26022e8fd2f.gif)

**Comment by TylerLeonhardt** [comment]
I think what you have there is good
