### ISSUE TITLE
Can't preview an HTML file in a Codespace

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-livepreview#365]
1. Checkout https://github.com/microsoft/vscode-dev-chrome-launcher/pull/20 in a GitHub codespace 
2. Preview options.html
3. :bug: preview doesn't work 
4. See notification about application running on forwarded port
5. :bug: open in browser also doesn't work -- I see a 401 error

**Comment by andreamah** [comment]
note to verifier:
- Use the prerelease of the extension
- You'll need to authorize both ports before you use live preview on codespaces (because of #111). Once you open the preview, go to the `Ports` panel and open the external links that are there for the http and websocket ports in your browser. This should authorize the private ports and allow you to use the extension.

**Comment by tharcissentirandekura** [comment]
Also you can install http port view by running  npm i -g http-server in the terminal and after installation, type http-server which will open the http port you can view the file. Then open the browser and paste the address : ex:  http://172.16.5.4:8080
