### ISSUE TITLE
File not found link immediately redirects back to original page

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode-livepreview#426]
Testing microsoft/vscode#172071

1. Create a link to a file that does not exist: `<a href="nosuch.html">text</a>`
2. Open the in app preview and click on the link

**Bug**
I see a `File not found` page for a fraction of a second but then end up back on the starting page

**Comment by andreamah** [comment]
Strange, I see different behavior in the pre-release when I use stable instead of insiders (although still not correct, since it assumes that it's an external link). Will need to look into this.

**Comment by andreamah** [comment]
> Strange, I see different behavior in the pre-release when I use stable instead of insiders (although still not correct, since it assumes that it's an external link). Will need to look into this.

Seems that I might have been using an old version, since I can't repro this anymore.

However, I notice that this bug doesn't happen on stable, only on insiders. I notice that the webview's iframe goes blank when I try to set the webview panel's title, and commenting out the line that sets the panel title seems to resolve the bug. @mjbvz do you know what might be going on with setting the panel title? Seems that this bug doesn't only affect navigating to non-existing pages, but also pages that exist.

**Comment by mjbvz** [comment]
Yes sounds like https://github.com/microsoft/vscode/issues/172391

**Comment by meganrogge** [comment]
I clicked on the link and it opened to the invalid page - is that as designed?

**Comment by andreamah** [comment]
> I clicked on the link and it opened to the invalid page - is that as designed?

yup!
