### ISSUE TITLE
Suggesting for new server root setting description 

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode-livepreview#428]
Testing https://github.com/microsoft/vscode/issues/172071

For the new `server root` setting, a few suggestions for the  wording:

- I don't know what the part about `This will not apply to the root of your drive if you are not in a workspace` means. Is this saying that the setting only works for files that are part of a workspace?

- `host the server from`  makes me some server is going to be copied into that folder. Instead can we make it clear this is the root path files are served from. For example, maybe start the description with something like: `The root path in the workspace that files are served from`

**Comment by andreamah** [comment]
> This will not apply to the root of your drive if you are not in a workspace

This essentially means that you can't have the setting be C:/test/, preview outside of a workspace, and expect the server to start from C:/test/. I guess that is sort of a confusing case that I'm not sure anyone would use. I should probably phrase it more like "The relative path from the workspace root that the files are served from" so that it's implied that having no workspace root nullifies this setting.

**Comment by isidorn** [comment]
Just like to add that the word "in" is missing in the current description:

The server root to host the server from. Files will be previewed as if the workspace root is at this offset. If this directory path doesn't exist **IN** your workspace, it will default to the workspace root. This will not apply to the root of your drive if you are not in a workspace.

**Comment by isidorn** [comment]
Should we also say this path should be relative?
