### ISSUE TITLE
Using with parcel

### ISSUE THREAD

**Issue by patrykK1028** [microsoft/vscode-livepreview#447]
So when I start Parcel, I get a link like this: http://localhost:1234/ I would like to use it in Live Preview, but when I do I get an error saying that Live Preview doesn't work with external hosts. Am I doing it wrong or is there no way to use Live Preview with Parcel?

**Comment by andreamah** [comment]
Looking at the documentation for Parcel, it looks like it starts its own server. Since Live Preview also starts a server and relies on the Live Preview server, you wouldn't be able to use Live Preview with it. You can get an "embedded" browser in your vscode instance by using `Simple Browser: Show` on your URL in this case.
