### ISSUE TITLE
Open Automatically on Server Start only works if the file is in the first workspace folder

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode-livepreview#455]
Verifying https://github.com/microsoft/vscode-livepreview/issues/274

It seems like the context menu flow only works if the file is in the first workspace folder. If it's in other workspace folders, it takes no effect.

Can probably loop through all workspace folder for a truthy value here

https://github.com/microsoft/vscode-livepreview/blob/5dc189d2136e08bf6e4ad782c991d22129a23ed3/src/extension.ts#L51-L52

...or save the setting in the Workspace instead of the WorkspaceFolder (using `vscode.workspace.rootPath` as the base for the relative path)

**Comment by andreamah** [comment]
Taking another look at this, wouldn't it be better to open it for whichever workspace folder you're in at the moment? (ie: look at your active file and see which workspace it belongs to; else if active file is undefined, default to first workspace). The reason why I don't check for a defined `defaultPreviewPath` where you linked is because that's just a basic `Start Server` command that doesn't really imply anything about needing a default preview path.

**Comment by connor4312** [comment]
This doesn't seem to work correctly if the same file exists in both workspaces. Debugging through, the right config is read and passed to `openPreviewAtFileString`, but then `PathUtil.getWorkspaceFromRelativePath` finds the first workspace folder instead of the second workspace folder.

Btw, I noticed the livepreview extension isn't set up for breakpoints to bind correctly. If you just delete the `outFiles` property in the launch.json, they'll work.

**Comment by andreamah** [comment]
Ah, I was wondering why breakpoints weren't binding. Thanks! Filed #477 for that.
