### ISSUE TITLE
The IP address cannot be used to host the server. Using default IP xxxxxx- error

### ISSUE THREAD

**Issue by Shihabsarker93** [microsoft/vscode-livepreview#588]
In vs code when I want to see preview using Live Preview extention. This error appears --
 "The IP address "xxxxxxxx cannot be used to host the server. Using default IP xxxxxx."

**Comment by andreamah** [comment]
Do you have the setting `livePreview.hostIP` set anywhere?

**Comment by vishalsharma123321** [comment]
> In vs code when I want to see preview using Live Preview extention. This error appears -- "The IP address "xxxxxxxx cannot be used to host the server. Using default IP xxxxxx."

I have already fixed the problem it took nearly 3 and a half hours. I just went to the extension setting and after searching for live preview you will find its setting and find this option which is = Live Preview: Host IP
The local IP host address to host your files on. here if your IP is good then it will show an extra option the the right side where the Host IP is written. if your IP is not working then you will find the option on the right side of the host IP just lick the extra option and you will find the IP that was showing the error and you have to just reset it. after resting it just uninstall the extension and reinstall it it will work for sure. if anyone has a problem can reach out to me because I can feel the pain of wasting hours on a simple problem.

**Comment by BhupendraMaurya** [comment]
I have reset the IP address, but option at top right corner is not visible in vs code, please tell me how to fix it.

**Comment by vishalsharma123321** [comment]
can you explain your problem more clearly?

**Comment by klren0312** [comment]
so how to do ???

**Comment by andreamah** [comment]
The fix for the problem is to delete the custom IP that you have in the `livePreview.hostIP ` setting and just set it to `127.0.0.1`

**Comment by theclickcreateco** [comment]
> The fix for the problem is to delete the custom IP that you have in the `livePreview.hostIP ` setting and just set it to `127.0.0.1`

Its worked

**Comment by nisha203001** [comment]
> > The fix for the problem is to delete the custom IP that you have in the `livePreview.hostIP ` setting and just set it to `127.0.0.1`
> 
> Its worked

yes it's working
