### ISSUE TITLE
Why doesn't the embedded preview version support external hosted links? Is this feature that difficult?

### ISSUE THREAD

**Issue by Super1Windcloud** [microsoft/vscode-livepreview#674]
if you can't  implement this function ,  I  have  no  choice but to  develop new plugin  for it

**Comment by andreamah** [comment]
Some external websites can't be framed due to the source code of the website itself. See https://medium.com/@kesen.somar.99/securing-your-website-how-to-disable-iframes-to-prevent-click-hijacking-attacks-98cd2004720f

Because of this, we disable all external websites by default. You can use `Simple Browser` in core VS Code (which is built into the editor) to preview external websites, but it still has the limitation mention above.
